apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world
spec:
  type: NodePort
  selector:
    app: flask-hello-world
  ports:
    - protocol: TCP
      port: 8000   #expose ip in minikube
      targetPort: 80   # expose ip in docker
      nodePort: 30080  #expose ip in local port
